image: node:20

stages:
  - install
  - lint
  - test
  - build
  - docker
  - deploy

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install

lint_job:
  stage: lint
  script:
    - npm run lint

unit_tests:
  stage: test
  script:
    - npm test

build_app:
  stage: build
  script:
    - echo "Application build successful"